name: Build Docker Image

on:
  push:
  release:
    types: [published]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: build-docker-image
    env:
      APP_NAME: xcube-geodb
      ORG_NAME: bcdev
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: get-release-tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: info
        id: info
        run: |
          echo "TAG: ${{ steps.release.outputs.tag }}"
          echo "EVENT: ${{ github.event_name }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build-push-docker-image-latest
        if: ${{ github.event_name == 'push' && steps.release.outputs.tag == 'master'  }}
        with:
          image: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}-lab
          tags: master, latest
          registry: quay.io
          username: ${{ secrets.QUAY_REG_USERNAME }}
          password: ${{ secrets.QUAY_REG_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build-push-docker-image-release
        if: ${{ github.event_name == 'release' }}
        with:
          image: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}-lab
          tags: ${{ steps.release.outputs.tag }}
          registry: quay.io
          username: ${{ secrets.QUAY_REG_USERNAME }}
          password: ${{ secrets.QUAY_REG_PASSWORD }}
